import './globals.css'
import type { Metadata } from 'next'
import LayoutChildren from './layout_children'
import QueryProvider from 'lib/query-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <LayoutChildren>
            {children}
          </LayoutChildren>
        </QueryProvider>
      </body>
    </html>
  )
}
